spring.application.name=gestaoproducao
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Configurações do Banco de Dados (MariaDB Docker)
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mydatabase}
spring.datasource.username=${DB_USER:myuser}
spring.datasource.password=${DB_PASSWORD:secret}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Configurações OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=profile,email

# Suporte a cabeçalhos de proxy (X-Forwarded-Host, X-Forwarded-Proto) para gerar as URLs de redirecionamento corretas atrás do Ngrok
server.forward-headers-strategy=framework
